blank_issues_enabled: false
contact_links:
  - name: ğŸ“ æŠ€è¡“æ”¯æ´
    url: https://www.utk.com.tw/
    about: å¦‚éœ€æŠ€è¡“æ”¯æ´ï¼Œè«‹é€éå®˜æ–¹ç¶²ç«™è¯çµ¡æˆ‘å€‘
  - name: ğŸ’¬ ä¸€èˆ¬è«®è©¢
    url: https://github.com/UTK-TW/.github/discussions
    about: ä¸€èˆ¬å•é¡Œè¨è«–èˆ‡äº¤æµ